apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-test1-kube-prometheus-stac-alertmanager
  namespace: monitor
  labels:
    app: kube-prometheus-stack
    chart: kube-prometheus-stack
    release: kubeprometheus-stack
type: Opaque

stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 2m

    route:
      receiver: discord
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 10m

      routes:
        - match:
            alertname: Watchdog
          receiver: null

    receivers:
      - name: discord
        webhook_configs:
          - url: "https://discord.com/api/webhooks/1508520943511797900/Y71CiEMYJowusqWNISDlOxZhYkvRW_fmQGnuojzVyMsXhWkGGJW-SLQvLL3Phpd6yj37"
            send_resolved: true
            http_config:
              follow_redirects: true

            title: '{{ .CommonLabels.alertname }}'

            message: |
              {{ range .Alerts }}
              Alert: {{ .Labels.alertname }}
              Severity: {{ .Labels.severity }}
              Namespace: {{ .Labels.namespace }}
              Pod: {{ .Labels.pod }}
              Status: {{ .Status }}
              Summary: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              {{ end }}

      - name: null