version: "3.8"

services:

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
 
      
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: appdb

  backend:
    build: ./backend
    container_name: node-backend
    restart: unless-stopped
   
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
volumes:
  mongo_data:
